//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartMaster
    {
        public int CartId { get; set; }
        public Nullable<int> Qnt { get; set; }
        public System.DateTime Date { get; set; }
        public int refUserId { get; set; }
        public int refProductId { get; set; }
        public bool OrderProcess { get; set; }

        public int Count { get; set; }
        public decimal Total { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }

        public string ShoppingCartId { get; set; }

    }
}
