//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMaster
    {
        public int LoginId { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public string LoginType { get; set; }
        public string LoginEmailId { get; set; }
    }
}
